<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Medical Abbreviations Lookup</title>
  <link rel="stylesheet" href="assets/css/styles.css">
</head>
<body>
  <header>
    <h1>Medical Abbreviations Lookup</h1>
    <p>Search for medical abbreviations used in prescriptions and clinical settings</p>
  </header>
  
  <div class="search-container">
    <input type="text" id="search-input" placeholder="Search abbreviations (e.g. 'dtd' for 'd.t.d')...">
    <button id="search-btn">Search</button>
    <button id="reset-btn">Reset</button>
  </div>
  
  <div class="categories">
    <button class="category-btn active" data-category="all">All Categories</button>
    <button class="category-btn" data-category="prescription">Prescription Filling</button>
    <button class="category-btn" data-category="quantities">Quantities & Measurement</button>
    <button class="category-btn" data-category="patient">Patient Instructions</button>
    <button class="category-btn" data-category="medications">Medications</button>
    <button class="category-btn" data-category="clinical">Clinical Conditions</button>
    <button class="category-btn" data-category="dosage">Dosage Forms/Vehicles</button>
    <button class="category-btn" data-category="routes">Routes of Administration</button>
  </div>
  
  <div class="abbreviations-container" id="abbreviations-container">
    <!-- Categories and tables will be generated by JavaScript -->
  </div>

  <script src="assets/js/abbreviations.js"></script>
</body>
</html>